<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WasabiDrive.WinFsp</RootNamespace>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WasabiDrive.Core\WasabiDrive.Core.csproj" />
    <ProjectReference Include="..\WasabiDrive.CloudFiles\WasabiDrive.CloudFiles.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="winfsp.net" Version="2.1.25156" />
  </ItemGroup>

</Project>
